// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'Android options are not manually configured in this file. It relies on google-services.json',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS options are not manually configured in this file. It relies on GoogleService-Info.plist',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not supported by this file.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not supported by this file.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported by this file.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI3vVtLC5WVj52nv6siayXcyBYM_Boe_4',
    appId: '1:353454091403:web:REPLACE_WITH_YOUR_WEB_APP_ID', // ⚠️ PLACEHOLDER
    messagingSenderId: '353454091403',
    projectId: 'flexion-flow',
    authDomain: 'flexion-flow.firebaseapp.com',
    storageBucket: 'flexion-flow.firebasestorage.app',
  );
}
